
[general]
	disable_mod = false
	auto_start = false
	space_modules = true
	shadow_text = true
	animations = true
	animationSpeed = 2.0
	fontScale = 1.0
	background_color = 1867534416
	hide_debug_crosshair = true
	hide_sidebar = true
	hide_bossbar = false
	always_show_profiler = false
	always_show_tps = false

[[modules_left]]
	name = "empty"
	empty_lines = 2
	enabled = true

	[modules_left.lines]
		nothing = true

[[modules_left]]
	name = "minecraft"
	name_color = 10506797
	value_color = 43520
	enabled = true

	[modules_left.lines]
		minecraft = true

[[modules_left]]
	name = "fps"
	color_high = 5635925
	color_med = 16777045
	color_low = 16733525
	enabled = true

	[modules_left.lines]
		fps = true

[[modules_left]]
	name = "coords"
	name_color = 16733525
	color_x = 16733525
	color_y = 5635925
	color_z = 5636095
	enabled = true

	[modules_left.lines]
		player_coords = true
		block_coords = true
		chunk_relative_coords = true
		chunk_coords = true

[[modules_left]]
	name = "location"
	name_color = 43520
	value_color = 5636095
	enabled = true

	[modules_left.lines]
		dimension = true
		facing = true
		rotation = true
		light = true
		light_server = true
		highest_block = true
		highest_block_server = true
		biome = true
		local_difficulty = true
		day_ticks = true
		days_played = true
		slime_chunk = true

[[modules_left]]
	name = "entity"
	name_color = 16733525
	value_color = 16777045
	total_entities_color = 16755200
	enabled = true

	[modules_left.lines]
		particles = true
		entities = true
		monster = true
		creature = true
		ambient = true
		axolotls = true
		underground_water_creature = true
		water_creature = true
		water_ambient = true
		misc = true
		ie_creature = true

[[modules_left]]
	name = "help"
	name_color = 16645526
	value_color = 5636095
	enabled_color = 5635925
	disabled_color = 16733525
	enabled = true

	[modules_left.lines]
		pie_graph = true
		fps_tps = true
		help = true

[[modules_right]]
	name = "empty"
	empty_lines = 2
	enabled = true

	[modules_right.lines]
		nothing = true

[[modules_right]]
	name = "system"
	name_color = 16755200
	value_color = 5636095
	enabled = true

	[modules_right.lines]
		time = true
		java_version = true
		memory_usage = true
		allocation_rate = true
		allocated_memory = true
		cpu = true
		display = true
		gpu = true
		opengl_version = true
		gpu_driver = true

[[modules_right]]
	name = "target"
	name_color = 43775
	value_color = 16777045
	enabled = true

	[modules_right.lines]
		targeted_block = true
		id_block = true
		block_states = true
		block_tags = true
		nothing = true
		targeted_fluid = true
		id_fluid = true
		fluid_states = true
		fluid_tags = true
		nothing2 = true
		targeted_entity = true

